### ISSUE TITLE
Consider renaming from gcx to something more specific to Cloud Functions (gcf?)

### ISSUE THREAD

**Issue by steren** [JustinBeckwith/gcx#17]
It seems that this package is manipulating Cloud Functions, which is not very explicit from its name `gcx`.
If the intent is to stay focused on GCF, maybe rename it to something else? like `gcf` or `gcfx`?

**Comment by JustinBeckwith** [comment]
I totally hear what you're saying.  In fullness of time - I'd like to include the ability to deploy to app engine from here as well :) Given that, and the churn a rename would cause - I think Imma going to stick with `gcx`.  Thanks for the suggestion!
